### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by anatol-grabowski** [atomictech/xlsx-write-stream#1]
I just wanted to drop by and say that the interface of this lib is cleaner and it supports more types of cells than the original library.
Just what I was looking for.
Thank you :)

**Comment by Jule-** [comment]
@anatol-grabowski thanks a lot for showing your support! 🙂 🙏  You've earned your #1 badge! 😄 

Hope you will enjoy playing with it! Do not hesitate to come back with issues, ideas or even PR. 😉
