### ISSUE TITLE
is it possible to use require() instead of import when using this package?

### ISSUE THREAD

**Issue by ajkim745c** [atomictech/xlsx-write-stream#7]
Ex.

I need something like 

const XLSXWriteStream = require('@atomictech/xlsx-write-stream'); (doesn't actually work)

instead of 

import XLSXWriteStream from '@atomictech/xlsx-write-stream';

if not how would I go about working around this issue?

**Comment by Jule-** [comment]
Hi,

You can require default export like that:
```js
const { default: XLSXWriteStream } = require('@atomictech/xlsx-write-stream');
```
or
```js
const XLSXWriteStream = require('@atomictech/xlsx-write-stream').default;
```

**Comment by ajkim745c** [comment]
Thanks so much for the quick response! Works amazing for my project!
