### ISSUE TITLE
Is it possible to keep date type hint on dates?

### ISSUE THREAD

**Issue by ajkim745c** [atomictech/xlsx-write-stream#9]
Basically what I mean by this is this:
When my dates are being written into the excel sheet and formatted through TypeStyleKey ('MM/DD/YY'), the type of data is listed as custom on the Excel sheet, however I want it to show date as the type specifically. Is this possible? 

![excelQ](https://user-images.githubusercontent.com/103782248/171821994-b92376b2-2ae9-4b4e-a8c8-12c6edab5e8f.png)

for more context the value being formatted is a date object 

`value = new Date(value);`

Thank you

**Comment by Jule-** [comment]
You can try to define your custom style binding as described here: https://github.com/atomictech/xlsx-write-stream#custom-styles

And try to find the right `numFmtId` that fits your needs here: https://docs.microsoft.com/fr-fr/dotnet/api/documentformat.openxml.spreadsheet.numberingformat?view=openxml-2.8.1

Another option is  is to save an empty `xlsx` file with 1 date cell, unzip it and check the style associated with the cell. For what I remember I think that dates are localized `formatCode` and so depending on your Excel configuration the date format is recognized or not.

**Comment by Jule-** [comment]
And I do not understand your `TypeStyleKey ('MM/DD/YY')` part since in the code by default it is `yyyy-mm-dd`:

https://github.com/atomictech/xlsx-write-stream/blob/1afd8ae2a6d3fb92d7235f1341f7b15c42b48545/src/templates/styles.js#L49-L50
